// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVwMFzuUKlVm3mdmR_CQNrDLFNp7Pr7sw',
    appId: '1:780280659953:web:40df9b9a968459abb38e50',
    messagingSenderId: '780280659953',
    projectId: 'glowspace-3ce5a',
    authDomain: 'glowspace-3ce5a.firebaseapp.com',
    storageBucket: 'glowspace-3ce5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI2dLRJMmySorphC_jMg9ijZW3teMs45E',
    appId: '1:780280659953:android:2dbfc9d2a13b3817b38e50',
    messagingSenderId: '780280659953',
    projectId: 'glowspace-3ce5a',
    storageBucket: 'glowspace-3ce5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8n6wX1YquOHshsKd5NdXaSb958vf6kDM',
    appId: '1:780280659953:ios:6852e86c06fe0b1ab38e50',
    messagingSenderId: '780280659953',
    projectId: 'glowspace-3ce5a',
    storageBucket: 'glowspace-3ce5a.firebasestorage.app',
    iosBundleId: 'com.beautyweb.beautyios',
  );
}
